jobs:
  - deployment: Deploy
    pool:
      vmImage: ${{ parameters.agentPool }}
    environment: ${{ parameters.environment }}
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
            - download: current
              displayName: 'Download artifacts'
              artifact: drop
            - download: current
              displayName: 'Download tfplan'
              artifact: ${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan
            - task: CopyFiles@2
              inputs:
                sourceFolder: '$(Pipeline.Workspace)/${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan'
                targetFolder: '$(Pipeline.Workspace)/drop/components/${{ parameters.component }}'
            - task: TerraformInstaller@0
              inputs:
                terraformVersion: ${{ parameters.terraformVersion }}
            - task: TerraformCLI@0
              displayName: Init - ${{ parameters.environment }} - ${{ parameters.component }}
              inputs:
                command: 'init'
                backendType: 'azurerm'
                ensureBackend: true
                backendServiceArm: '${{ parameters.service_connection }}'
                backendAzureRmResourceGroupName: '${{ parameters.storage_account_rg }}'
                backendAzureRmStorageAccountName: '${{ parameters.storage_account_name }}'
                backendAzureRmResourceGroupLocation: 'uksouth'
                backendAzureRmContainerName: 'tfstate'
                backendAzureRmKey: '${{ parameters.component }}.tfstate'
                workingDirectory: '$(Pipeline.Workspace)/drop/components/${{ parameters.component }}'
              continueOnError: true
            - task: TerraformCLI@0
              displayName: Apply - ${{ parameters.environment }} - ${{ parameters.component }}
              name: tfapply${{ parameters.environment }}${{ parameters.component }}
              inputs:
                command: 'apply'
                commandOptions: '${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan'
                environmentServiceName: '${{ parameters.service_connection }}'
                workingDirectory: '$(Pipeline.Workspace)/drop/components/${{ parameters.component }}'
            - task: AzureCLI@2
              displayName: UnlockTFstateIfLocked
              condition: always()
              inputs:
                azureSubscription: '${{ parameters.service_connection }}'
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  leaseExist=`az storage blob show --container-name tfstate --name ${{ parameters.component }}.tfstate --account-name ${{ parameters.storage_account_name }}' | jq -r '.properties.lease.state'`
                  
                  if [ ${leaseExist} = "leased" ]; then
                    az storage blob lease break --blob-name ${{ parameters.component }}.tfstate --container-name tfstate --account-name ${{ parameters.storage_account_name }}
                  else
                    exit 0
                  fi