jobs:
  - job: Plan_${{ parameters.environment }}_${{ parameters.component }}
    pool:
      vmImage: ${{ parameters.agentPool }}
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: ${{ parameters.terraformVersion }}
#      - task: TerraformCLI@0
#        displayName: Init - ${{ parameters.environment }} - ${{ parameters.component }}
#        inputs:
#          command: 'init'
#          commandOptions: '-lock=false' # don't lock on PRs / validate phase
#          backendType: 'azurerm'
#          backendServiceArm: 'dcd-cftapps-${{ parameters.environment }}'
#          backendAzureRmResourceGroupName: 'core-infra-${{ parameters.environment }}-rg'
#          backendAzureRmStorageAccountName: 'cftapps${{ parameters.environment }}'
#          backendAzureRmContainerName: 'tfstate'
#          backendAzureRmKey: '${{ parameters.component }}.tfstate'
#          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'

# Temporary section for using forked version of tf provider (exclusions support)
#      - task: Bash@3
#        displayName: "Debug subdir"
#        inputs:
#          targetType: 'inline'
#          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
#          script: 'ls -lash .terraform/plugins/linux_amd64'

      - task: Bash@3
        displayName: Download forked TF provider
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          script: |
            wget https://github.com/hmcts/terraform-provider-azurerm/releases/download/v1.41.0-hmcts/terraform-provider-azurerm-linux_amd64 -O terraform-provider-azurerm
            mkdir -p .terraform/plugins/linux_amd64/
            cp terraform-provider-azurerm .terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.41.0_x4
            chmod +x .terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.41.0_x4

      - task: Bash@3
        displayName: "Debug dir"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          script: 'ls -lash'

      - task: Bash@3
        displayName: "Debug subdir"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          script: 'ls -lash .terraform/plugins/linux_amd64'

      - task: Bash@3
        displayName: "Debug version"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          script: 'terraform version'

      - task: TerraformCLI@0
        displayName: Init - ${{ parameters.environment }} - ${{ parameters.component }}
        inputs:
          command: 'init'
          commandOptions: '-lock=false' # don't lock on PRs / validate phase
          backendType: 'azurerm'
          backendServiceArm: 'dcd-cftapps-${{ parameters.environment }}'
          backendAzureRmResourceGroupName: 'core-infra-${{ parameters.environment }}-rg'
          backendAzureRmStorageAccountName: 'cftapps${{ parameters.environment }}'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '${{ parameters.component }}.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
# End Temporary section for using forked version of tf provider (exclusions support)

      - task: TerraformCLI@0
        displayName: Plan - ${{ parameters.environment }} - ${{ parameters.component }}
        inputs:
          command: 'plan'
          commandOptions: '-out=${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan -var-file=$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}.tfvars'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          environmentServiceName: 'dcd-cftapps-${{ parameters.environment }}'
      - task: Bash@3
        displayName: "Remove local tfstate"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          script: |
            rm -f terraform.tfstate* && rm -rf .terraform/
      - publish: $(System.DefaultWorkingDirectory)/components/${{ parameters.component }}/${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan
        artifact: ${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan
