variable env {}
variable "subscription" {}
variable project {}
variable location {}
variable "common_tags" {}
variable "frontends" {}
variable "subscription_id" {}
variable "enable_ssl" {}
variable "ssl_mode" {}
variable "resource_group" {}
variable "certificate_key_vault_name" {}
variable "oms_env" {}
variable "certificate_name_check" {}
