---
repos:
  # renovate: datasource=github-releases
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true
  # renovate: datasource=github-tags
  - repo: https://github.com/hmcts/pre-commit-hooks
    rev: 0.0.2
    hooks:
      - id: app_gateway_backend_check
