repos:
- repo: local
  hooks:
    - id: terraform_fmt
      name: Terraform fmt
      entry: terraform fmt -recursive
      language: system
      files: \.tf$
      pass_filenames: false
- repo: https://github.com/hmcts/pre-commit-hooks
  rev: 0.0.4
  hooks:
    - id: app_gateway_backend_check
