# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - /modules/azure-landing-zone/*
    - /components/global/*

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-18.04
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: cft-platform
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
    - plan
    - apply
    - destroy

  - name: environment_components
    type: object
    default:
    - deployment: 'sbox_cftapps_cluster_lb'
      environment: 'sbox'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_cftapps_cluster_lb_backend'
      environment: 'sbox'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_shutter'
      environment: 'sbox'
      component: 'shutter'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'sbox_private_dns'
      environment: 'sbox'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-sbox'
      storage_account_rg: 'core-infra-sbox-rg'
      storage_account_name: 'cftappssbox'
      dependsOn: 'Precheck'

    - deployment: 'ptl_dynatrace_activegate'
      environment: 'ptl'
      component: 'dynatrace_activegate'
      service_connection: 'DTS-CFTPTL-INTSVC'
      storage_account_rg: 'core-infra-intsvc-rg'
      storage_account_name: 'cftptlintsvc'
      dependsOn: 'Precheck'

    - deployment: 'ithc_cftapps_cluster_lb'
      environment: 'ithc'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-ithc'
      storage_account_rg: 'core-infra-ithc-rg'
      storage_account_name: 'cftappsithc'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'ithc_cftapps_cluster_lb_backend'
      environment: 'ithc'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-ithc'
      storage_account_rg: 'core-infra-ithc-rg'
      storage_account_name: 'cftappsithc'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'ithc_private_dns'
      environment: 'ithc'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-ithc'
      storage_account_rg: 'core-infra-ithc-rg'
      storage_account_name: 'cftappsithc'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'demo_cftapps_cluster_lb_backend'
      environment: 'demo'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-demo'
      storage_account_rg: 'core-infra-demo-rg'
      storage_account_name: 'cftappsdemo'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'demo_private_dns'
      environment: 'demo'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-demo'
      storage_account_rg: 'core-infra-demo-rg'
      storage_account_name: 'cftappsdemo'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'test_cftapps_cluster_lb'
      environment: 'test'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-test'
      storage_account_rg: 'core-infra-test-rg'
      storage_account_name: 'cftappstest'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'test_cftapps_cluster_lb_backend'
      environment: 'test'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-test'
      storage_account_rg: 'core-infra-test-rg'
      storage_account_name: 'cftappstest'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'test_cftapps_private_dns'
      environment: 'test'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-test'
      storage_account_rg: 'core-infra-test-rg'
      storage_account_name: 'cftappstest'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'stg_cftapps_cluster_lb'
      environment: 'stg'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-stg'
      storage_account_rg: 'core-infra-stg-rg'
      storage_account_name: 'cftappsstg'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'stg_cftapps_cluster_lb_backend'
      environment: 'stg'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-stg'
      storage_account_rg: 'core-infra-stg-rg'
      storage_account_name: 'cftappsstg'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'stg_private_dns'
      environment: 'stg'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-stg'
      storage_account_rg: 'core-infra-stg-rg'
      storage_account_name: 'cftappsstg'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'prod_cftapps_cluster_lb'
      environment: 'prod'
      component: 'cftapps_cluster_lb'
      service_connection: 'dcd-cftapps-prod'
      storage_account_rg: 'core-infra-prod-rg'
      storage_account_name: 'cftappsprod'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'prod_cftapps_cluster_lb_backend'
      environment: 'prod'
      component: 'cftapps_cluster_lb_backend'
      service_connection: 'dcd-cftapps-prod'
      storage_account_rg: 'core-infra-prod-rg'
      storage_account_name: 'cftappsprod'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'prod_shutter'
      environment: 'prod'
      component: 'shutter'
      service_connection: 'dcd-cftapps-prod'
      storage_account_rg: 'core-infra-prod-rg'
      storage_account_name: 'cftappsprod'
      dependsOn: 'sbox_cftapps_cluster_lb'

    - deployment: 'prod_private_dns'
      environment: 'prod'
      component: 'cftapps_private_dns'
      service_connection: 'dcd-cftapps-prod'
      storage_account_rg: 'core-infra-prod-rg'
      storage_account_name: 'cftappsprod'
      dependsOn: 'sbox_cftapps_cluster_lb'


stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'azurerm-sandbox'


  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              component: ${{ deployment.component }}
              serviceConnection: ${{ deployment.service_connection }}
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
              product: ${{ variables.product }}
