variable env {}
variable "subscription" {}
variable project {}
variable component {}
variable location {}
variable "common_tags" {}
variable "waf_mode" {}
variable "frontends" {}
variable "subscription_id" {}
variable "enablessl" {}
variable "sslMode" {}
variable "resource_group" {}