#!/bin/bash

echo "Terraform import started!"

line=$(sed '1q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_zone.ithc_zone $line
c=0 && line=$(sed '2q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_ns_record."this[0]" $line
c=1 && line=$(sed '3q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[0]" $line
c=2 && line=$(sed '4q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[1]" $line
c=3 && line=$(sed '5q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[2]" $line
c=4 && line=$(sed '6q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_a_record."this[0]" $line
c=5 && line=$(sed '7q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[3]" $line
c=6 && line=$(sed '8q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[4]" $line
c=7 && line=$(sed '9q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[5]" $line
c=8 && line=$(sed '10q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[6]" $line
c=9 && line=$(sed '11q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_mx_record."this[0]" $line
c=10 && line=$(sed '12q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_txt_record."this[0]" $line
c=11 && line=$(sed '13q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_txt_record."this[1]" $line
c=12 && line=$(sed '14q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[7]" $line
c=13 && line=$(sed '15q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[8]" $line
c=14 && line=$(sed '16q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[9]" $line
c=15 && line=$(sed '17q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_a_record."this[1]" $line
c=16 && line=$(sed '18q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[10]" $line
c=17 && line=$(sed '19q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[11]" $line
c=18 && line=$(sed '20q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[12]" $line
c=19 && line=$(sed '21q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[13]" $line
c=20 && line=$(sed '22q;d' ithc.platform.hmcts.net-resource-ids.txt) && terraform import -var 'env=ithc' -var 'ithc-platform-hmcts-net=ithc.platform.hmcts.net'  -var 'resource_group_name=reformmgmtrg' -backup=terraform.local.tfstate.backup module.public-dns.azurerm_dns_cname_record."this[14]" $line

echo "Terraform import completed!"